### ISSUE TITLE
`core.chk` can't distinguish type Int and float on second parameter?

### ISSUE THREAD

**Issue by EmbraceLife** [fastai/fastai_dev#133]
I hope the following code snapnot makes my issue clear. my code snippet is [here](https://github.com/EmbraceLife/my-v2/blob/master/core.chk.py#L25)

![image](https://user-images.githubusercontent.com/8749266/58761987-f9820f00-857c-11e9-9c95-9c56886905e3.png)

**Comment by shashankp** [comment]
Python does the type conversion just like in the case of [mixed arithmetic](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex)
