### ISSUE TITLE
Comments linking to inaccessible forum pages

### ISSUE THREAD

**Issue by marii-moe** [fastai/fastai_dev#134]
There are parts of the notebooks that link to forum pages that are inaccessible by students. Such as: 
(notebook 4 (callbacks) in swift)
    /// A wrapper class to hold the loss function, to work around
    // https://forums.fast.ai/t/fix-ad-crash-in-learner/42970.

This makes it very difficult to determine why "weird" decisions were made, which is fairly important when trying to understand how the underlying code is working. 

Sadly I cannot fix this myself as I do not have access to this part of the forum.

**Comment by jph00** [comment]
@marii-moe If you let me know what needs to be fixed, I'll get it sorted :)
