### ISSUE TITLE
notebook2script.py requires fastai_v1 for fastai.script

### ISSUE THREAD

**Issue by kevinbird15** [fastai/fastai_dev#153]
It seems weird to have this line in [notebook2script.py](https://github.com/fastai/fastai_dev/blob/e237255dd12f7124f8cc51370e8556c6b2056aca/dev/notebook2script.py#L4):

```
from fastai.script import *
```

Is there a way to bring fastai_v1 script into fastai_v2 to remove this dependency?

Here is what is being imported: 

https://github.com/fastai/fastai/blob/master/fastai/script.py

**Comment by kevinbird15** [comment]
It looks like this may only be used in 90_notebook_core because 91_notebook_export creates this functionality for fastai_v2 itself.

**Comment by sgugger** [comment]
The fastai v1 script was already in v2, it was just a typo :)
