### ISSUE TITLE
Docs bug

### ISSUE THREAD

**Issue by jph00** [fastai/fastai_dev#164]
@sgugger there's a bug in the generated docs. The issue is that the "ID=" attribute in the HTML includes the "\<code>" tags, so anchor hyperlinks don't work. for instance, this doesn't work: 
http://dev.fast.ai/data.pipeline.html#Transform

**Comment by sgugger** [comment]
Fixed and tested, see http://dev.fast.ai/data.pipeline.html#Pipeline
