### ISSUE TITLE
Bug in nb_002c and nan loss in 006b_pascal training

### ISSUE THREAD

**Issue by shang-vikas** [fastai/fastai_dev#203]
Hi,
I was going through pascal notebook and got the below error while trying to execute `show` method.

```
~/my-work/fastai_dev/dev_nb/nb_002c.py in _perspective_warp(c, targ_pts)
     37 def _perspective_warp(c:FlowField, targ_pts:Points):
     38     "Apply warp to `targ_pts` from `_orig_pts` to `c` `FlowField`"
---> 39     return apply_perspective(c, find_coeffs(_orig_pts, targ_pts))
     40 
     41 @TfmCoord

~/my-work/fastai_dev/dev_nb/nb_002c.py in find_coeffs(orig_pts, targ_pts)
     20     B = FloatTensor(orig_pts).view(8)
     21     #The 8 scalars we seek are solution of AX = B
---> 22     return torch.gesv(B,A)[0][:,0]
     23 
     24 def apply_perspective(coords:FlowField, coeffs:Points)->FlowField:

AttributeError: module 'torch' has no attribute 'gesv'

```
Quickly went through the pytorch code where they stated `.gesv` has been removed in 1.2.0 version and advised to use `.solve`.
please change `torch.gesv(B,A)[0][:,0]` to  `torch.solve(B.reshape(-1,1),A)[0][:,0]`  as i dont know how to make a PR to fastai.:grimacing: sorry.

Second thing is that i am getting a `nan` loss in learner.lr_find() as well as while training, dont know the reason. I will try to debug more into it.Any help on how to do that will be appreciated.

**Comment by sgugger** [comment]
Those notebooks are there as an history of the development of fastai v1, they are not supposed to work with the latest pytorch version but 1.0.0.
