### ISSUE TITLE
issues with get_preds

### ISSUE THREAD

**Issue by 313v** [fastai/fastai_dev#225]
1) call get_preds on a learner that hasn't done any training causes problems with non-existent variables (uninitialized)

so for example:

```
channels = 1
num_cat =7
opt_func = partial(Adam, lr=3e-3, wd=0.01)
model = xresnet.xresnet18(c_in=channels,c_out=num_cat)
cb_funcs = [partial(MixedPrecision, clip=0.1)]
metrics = [accuracy_multi]
test_learn = Learner(test_dbunch, model, opt_func=opt_func, loss_func=BCEWithLogitsLossFlat(), 
                cb_funcs=cb_funcs, metrics=metrics)

test_learn = test_learn.load('test')

preds, targets = test_learn.get_preds(ds_idx=0)
```

will throw exceptions about missing variables on learner if I don't do something like this instead:
```
test_learn.n_epoch = 1
test_learn.epoch = 0
test_learn.smooth_loss = 0.
preds, targets = test_learn.get_preds(ds_idx=0)
```
the first two exceptions are tied to the progress_callback i believe - i think because in training we use _do_begin_fit and we don't with get_preds

2) calling get preds with a dataset that isn't evenly divisible by batch size throws an exception on the last partial batch

**Comment by sgugger** [comment]
The two should be fixed now.
