### ISSUE TITLE
loss smoothing leads to a jump / fall on graph before it kicks in

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai_dev#227]
Example of the behavior below:

![image_2019_09_28T05_38_17_362Z](https://user-images.githubusercontent.com/2444926/65820910-0105ac00-e22f-11e9-864a-aa73cb922df5.png)

Main concern is that this might lead to misrepresentation - "oh, so I unfroze another param group and now this jump on the first batch - probably I this means I am doing something wrong"

**Comment by sgugger** [comment]
We skipped the first losses in plots in v1 for this reason. Since the smooth loss is reset at each call to fit, it's bound to have a bumpy beginning.
