### ISSUE TITLE
create_cnn_model not cutting archs properly

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai_dev#229]
If my understanding is correct, the following should give 3 param groups. Instead it gives one:

![image](https://user-images.githubusercontent.com/2444926/65821116-a6ba1a80-e231-11e9-9a96-fdb8e84418c2.png)

**Comment by sgugger** [comment]
`create_cnn_model` isn't responsible for splitting, that's the `splitter` you pass to `Learner` that does this. `create_cnn_model` just puts a body from a pretrained arch and a head together. You can read more about it in `cnn_learner` in 22.
