### ISSUE TITLE
learn.validate output is incorrectly formatted

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai_dev#231]
With custom metrics it does not include valid loss and everything gets shifted by one to the left:
![image](https://user-images.githubusercontent.com/2444926/65834644-7a5bd800-e2dd-11e9-88fc-86f344f7c498.png)

**Comment by sgugger** [comment]
Fixed by an earlier commit, the output of the progress bar is not left in `Learner.validate()==` now.
