### ISSUE TITLE
train - save - restart notebook - load - train - save raises an error

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai_dev#240]
I documented the behavior in this [example notebook](https://github.com/radekosmulski/fastai_dev/blob/example2/dev/example.ipynb).

**Comment by sgugger** [comment]
The problem is in your custom splitter. The last group it returns is not a list but a single parameter. Changing it to:
```
def splitter(model):
    return params(model)[:150], params(model)[150:-1], params(model)[-1]
```
makes the bug disappear for me. I'll add some checks in optimizer in any case.
