### ISSUE TITLE
get_files incorrectly includes folders if passed as str, not list

### ISSUE THREAD

**Issue by kdorichev** [fastai/fastai_dev#242]
Current implementation of `get_files()` when receives `folders` parameter as `str` fails to distinguish folders that are included in the passed parameter, for example:
`train` in `training` will be `True` while should be `False`.
**A fix**: cast `folders` to `L` type in the beginning of the function.
```
folders = L(folders)
```
https://github.com/fastai/fastai_dev/blob/ee9b845f26cc8f0430bba27555b02307ad594f64/dev/local/data/transforms.py#L34

**Comment by kdorichev** [comment]
Please assign to me to fix, if you please.

**Comment by sgugger** [comment]
Fixed by #244
