### ISSUE TITLE
Wikitext-2 integration test failing due to LMDataLoader setting unsettable TfmdDL `items` property

### ISSUE THREAD

**Issue by dcato98** [fastai/fastai_dev#252]
LMDataLoader expects to be able to set `items`, however this is defined in `TfmdDL` as a property with no setter, which raises 'AttributeError: can't be called' when creating a text databunch (e.g. in the wikitext-2 integration test).

Error thrown in 35_tutorial_wikitext.ipynb:
```python
dbch = dsrc.databunch(bs=bs, seq_len=sl, after_batch=Cuda)
```

31_text_data.ipynb:
```python
class LMDataLoader(TfmdDL):
    def __init__(self, dataset, lens=None, cache=2, bs=64, seq_len=72, num_workers=0, **kwargs):
        super().__init__(dataset=dataset, bs=bs, num_workers=num_workers, **kwargs)
        self.items = ReindexCollection([(o[0] if isinstance(o, tuple) else o)
                                        for o in dataset], cache=cache)
```

05_data_core.ipynb:
```python
class TfmdDL(DataLoader):
    @property
    def items(self): return self.tls[0].items
```

Removing the `items` property from `TfmdDL` and re-exporting the notebook fixed the immediate issue, but I'm too new to this library to determine whether this is the right fix. I'd be happy to submit a PR if it is.

Not sure whether this is relevant, but I also noticed that the `items` property references a `tls` attribute, which doesn't seem to exist for a DataLoader, but does exist in a DataSource - perhaps something got mixed up here?

**Comment by sgugger** [comment]
This is fixed now, thanks for flagging!
