### ISSUE TITLE
Wikitext datasets do not have valid.csv as referred in 35_tutorial_wikitext 

### ISSUE THREAD

**Issue by kdorichev** [fastai/fastai_dev#255]
Wikitext datasets (WIKITEXT, WIKITEXT_TINY) do not have *.**txt** files, but *.**csv**, and no **valid.csv**, as expected/referred to in the 35_tutorial_wikitext notebook:
```
path = untar_data(URLs.WIKITEXT_TINY)
!ls $path
test.csv  train.csv
...
val_txt = read_file(path/'valid.txt')
```

**Comment by kdorichev** [comment]
Also [PR submitted](https://github.com/fastai/course-v3/pull/421) to update correct URLs to the WIKITEXT* datasets.

**Comment by sgugger** [comment]
Fixed, our dataset is different from the original and I had built the tutorial on the original.
