### ISSUE TITLE
mixup doesn't work - self.in_train not found

### ISSUE THREAD

**Issue by rmkn85** [fastai/fastai_dev#256]
Tried to use Mixup, like in the notebook:
https://github.com/fastai/fastai_dev/blob/master/dev/19_callback_mixup.ipynb

```
mixup = MixUp(0.5)
learn = Learner([...], cbs=mixup)
```

But getting self.in_train (which is referred in MixUp.lf()) not found. Indeed I [didn't find it](https://github.com/fastai/fastai_dev/search?q=in_train&unscoped_q=in_train) anywhere in the code.

**Comment by dcato98** [comment]
I submitted a PR to fix this. In the meantime, try running this after importing MixUp:

```python
@patch
def begin_batch(self:MixUp):
    if not self.training: return
    lam = self.distrib.sample((self.y.size(0),)).squeeze().to(self.x.device)
    lam = torch.stack([lam, 1-lam], 1)
    self.lam = lam.max(1)[0]
    shuffle = torch.randperm(self.y.size(0)).to(self.x.device)
    xb1,self.yb1 = tuple(L(self.xb).itemgot(shuffle)),tuple(L(self.yb).itemgot(shuffle))
    nx_dims = len(self.x.size())
    self.learn.xb = tuple(L(xb1,self.xb).map_zip(torch.lerp,weight=unsqueeze(self.lam, n=nx_dims-1)))
```

**Comment by rmkn85** [comment]
`nx_dims` assignment is commented out, and then used in next line?

**Comment by dcato98** [comment]
Oops, good catch. I've updated my previous comment.

**Comment by sgugger** [comment]
Pr merged, so this should be fixed. Thanks!
