### ISSUE TITLE
Import Error on import fastai2.basics

### ISSUE THREAD

**Issue by dcoukos** [fastai/fastai_dev#258]
Hello! 

Just installed fastai v2 on a kaggle kernel following instructions from Jeremy Howard's [notebook](https://www.kaggle.com/jhoward/some-dicom-gotchas-to-be-aware-of-fastai).

Running  `import fastai2.basics` results in the traceback linked below. I'm fairly inexperienced with python, but this seems like an issue within fastai to me.

>  ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-6-6b515b6b493b> in <module>
> ----> 1 import fastai2.basics
> 
> /opt/conda/lib/python3.6/site-packages/fastai2/basics.py in <module>
> ----> 1 from .data.all import *
>       2 from .optimizer import *
>       3 from .learner import *
>       4 from .metrics import *
> 
> /opt/conda/lib/python3.6/site-packages/fastai2/data/all.py in <module>
> ----> 1 from ..torch_basics import *
>       2 from .core import *
>       3 from .load import *
>       4 from .external import *
>       5 from .transforms import *
> 
> /opt/conda/lib/python3.6/site-packages/fastai2/torch_basics.py in <module>
>       1 from .core.all import *
> ----> 2 from .torch_imports import *
>       3 from .torch_core import *
>       4 from .layers import *
> 
> /opt/conda/lib/python3.6/site-packages/fastai2/torch_imports.py in <module>
> ----> 1 import torch
>       2 from torch import as_tensor,Tensor,ByteTensor,LongTensor,FloatTensor,HalfTensor,DoubleTensor
>       3 import torch.nn as nn
>       4 import torch.nn.functional as F
>       5 from torch.utils.data import SequentialSampler,RandomSampler,Sampler,BatchSampler
> 
> /opt/conda/lib/python3.6/site-packages/torch/__init__.py in <module>
>      79 del _dl_flags
>      80 
> ---> 81 from torch._C import *
>      82 
>      83 __all__ += [name for name in dir(_C)
> 
> ImportError: libshm.so: cannot open shared object file: No such file or directory

**Comment by sandreel** [comment]
Interesting. I am trying the same and for me also the `import fastai2.basics` command is failing, however already a bit earlier... 

>>> from fastai2.basics import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/anaconda3/envs/medical_image/lib/python3.7/site-packages/fastai2/basics.py", line 1, in <module>
    from .data.all import *
  File "<...>/anaconda3/envs/medical_image/lib/python3.7/site-packages/fastai2/data/all.py", line 1, in <module>
    from ..torch_basics import *
  File "<...>/anaconda3/envs/medical_image/lib/python3.7/site-packages/fastai2/torch_basics.py", line 1, in <module>
    from .core.all import *
ModuleNotFoundError: No module named 'fastai2.core'

**Comment by dcoukos** [comment]
This must have been fixed in a recent commit. This error no longer appears on a fresh install of fastai2
