### ISSUE TITLE
Can't setup batch transforms from TfmdDL

### ISSUE THREAD

**Issue by slawekslex** [fastai/fastai_dev#259]
The Transform.setup() is called before the TfmdDL super constructor [here](https://github.com/fastai/fastai_dev/blob/a22a9882b38c778059668058a50ca5b84f6c6f51/dev/local/data/core.py#L45)
As the result the transform wont have access to the data. See for example:
```
class foo(Transform):
    def setup(self, items):
        n = len(items)
test_ds = DataSource(L(range(10)))
test_dl = TfmdDL(test_ds,bs=2,after_batch=[foo])
```

**Comment by sgugger** [comment]
What is your use case? I think they should be passed self.dataset for the setup but want to be sure that's  what you need.

**Comment by slawekslex** [comment]
Getting the dataset sounds good.

**Comment by sgugger** [comment]
Just fixed this, the setup gets passed the full `DataLoader` in the end. Pipelines are setup in the logical order: after_item, before_batch and after_batch.
