### ISSUE TITLE
notebook2script.py tries import from non-existing module

### ISSUE THREAD

**Issue by kdorichev** [fastai/fastai_dev#265]
https://github.com/fastai/fastai_dev/blob/b62fcfe3c2ad3d71465556c1a6b3235f38fa8f98/dev/notebook2script.py#L4

**Comment by misza222** [comment]
Pull request dealing with this problem https://github.com/fastai/fastai_dev/pull/268

**Comment by sgugger** [comment]
PR merged, so this should be fixed.
