### ISSUE TITLE
kornia is not part of dependencies on pip install

### ISSUE THREAD

**Issue by dcoukos** [fastai/fastai_dev#266]

**Comment by dcoukos** [comment]
Hi, 

Working with a fresh install of fastai dev from a few minutes ago. Calling `from fastai2.basics import * ` or `from fastai2.medical.imaging import *` results in an import error since the package kornia has not been installed. 

Pip installing kornia fixed this minor issue.

**Comment by sgugger** [comment]
Yes, it's an additional dependency to use the medical.imaging part of the library, but not a core dependency, so the user is required to install it separately.
