### ISSUE TITLE
Found a bug in dev/local/vision/augment.py

### ISSUE THREAD

**Issue by DollofCuty** [fastai/fastai_dev#274]
I think this line of code does not belong here
https://github.com/fastai/fastai_dev/blob/e71599422e8af6ff95cabda0700da9c18c176679/dev/local/vision/augment.py#L624

it originally came from this commit:
https://github.com/fastai/fastai_dev/commit/a16685d72bd4de144175ec8da334db1d8a6a3db7

and everything except this line was corrected here:
https://github.com/fastai/fastai_dev/commit/e71599422e8af6ff95cabda0700da9c18c176679

If I understood what happened correctly the line should be replaced by:
`if do_flip:    res.append(Dihedral(p=0.5, **tkw) if flip_vert else Flip(p=0.5, **tkw))`

I'd be glad to do the PR

**Comment by sgugger** [comment]
Oh yes, that's not good. Thanks for flagging this! Since it's a bit urgent I'll make the change immediately, in the future, for a problem where you have the solution, just open a PR instead of an issue. Worst case scenario, we'll close it instead of merging it :)
