### ISSUE TITLE
Fastai2 Lesson One Import Problem

### ISSUE THREAD

**Issue by gorillya** [fastai/fastai_dev#280]
Inputting lesson 2 into colab I got an error on import of library:

from fastai2.callback.all import *

error reads:

AttributeError                            Traceback (most recent call last)

<ipython-input-33-4e657a62af4a> in <module>()
      1 from fastai2.basics import *
----> 2 from fastai2.callback.all import *
      3 from fastai2.vision import *
      4 from fastai2.notebook.showdoc import *

2 frames

/usr/local/lib/python3.6/dist-packages/fastai2/vision/core.py in <module>()
     20 #Cell
     21 if not hasattr(Image,'_patched'):
---> 22     _old_sz = Image.Image.size.fget
     23     @patch_property
     24     def size(x:Image.Image): return Tuple(_old_sz(x))

AttributeError: type object 'Image' has no attribute 'size'

Then checked PIL image module and indeed it does have size - it also has,

Image.resize(size, resample=0)

Is that what is meant?

**Comment by sgugger** [comment]
Are you sure you have the latest version of fastai v2? I can't reproduce this and it all runs fine for me.

**Comment by muellerzr** [comment]
Pillow needs to be updated. 
`!pip install Pillow --upgrade`

**Comment by gorillya** [comment]
Worked! Now I have new problems coming up later in the notebook - but that is a story for another day :)

**Comment by muellerzr** [comment]
Check my repo for colab notebooks 

https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0

**Comment by gorillya** [comment]
> Check my repo for colab notebooks
> 
> https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0

This is amazing! and should be put somewhere prominent so that people can go through it as an overview to Fast2 (2Fast2FurAi)
