### ISSUE TITLE
Colab Specific: RuntimeError: inverse_cuda: For batch 0: U(17437184,17437184) is zero, singular U.

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai_dev#286]
Just leaving this here so it's known about (and many others are aware of this problem). This is currently a problem with Magma, Google Colaboratory and the transforms, especially `TensorPoint`'s among others. This problem is currently being worked on here: https://github.com/pytorch/pytorch/issues/29096

You can reproduce this by trying to do the Image Regression problem from the course in Google Colab.

I will update when it's working again. Sylvain if you want this to be closed (instead of left open) go ahead, but I felt having this here would be easier than a million questions opening up from Colab users :)

**Comment by sgugger** [comment]
No worries, thanks for investigating the issue!

**Comment by muellerzr** [comment]
The fix is done, should come out with Colab version 1.3.1

**Comment by muellerzr** [comment]
This issue has been solved. Recommend requiring torch 1.3.1 as this contains the fix
