### ISSUE TITLE
skimage missing in README

### ISSUE THREAD

**Issue by KeremTurgutlu** [fastai/fastai_dev#300]
Note in README.md "To use `fastai2.medical.imaging` you'll also need to:" is missing `skimage` dependency.

**Comment by sgugger** [comment]
I never got a complain on a fresh install, isn't it automatically installed by some of the other dependency?

**Comment by KeremTurgutlu** [comment]
Following the steps:
1) clone https://github.com/fastai/fastai_dev/
2) cd to `fastai_dev`
3) conda env create -f environment.yml
4) conda activate fastai_dev

looks like `scikit-image` library is not  dependency of any of the others
