### ISSUE TITLE
Error on pip install git+https://github.com/fastai/fastai_dev on Kaggle

### ISSUE THREAD

**Issue by Pyligent** [fastai/fastai_dev#304]
It just happened since last night. When trying to "pip install git+https://github.com/fastai/fastai_dev" on Kaggle(Try RSNA competition), the ERROR appears. (It works fine before yesterday). Thanks so much for the help!

**Error Messages:**
Running command git clone -q https://github.com/fastai/fastai_dev /tmp/pip-req-build-8uxrwu7_
  ERROR: Could not find a version that satisfies the requirement fastprogress>=0.1.22 (from fastai2==2.0.1) (from versions: 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.12, 0.1.13, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21)
ERROR: No matching distribution found for fastprogress>=0.1.22 (from fastai2==2.0.1)

**Comment by sgugger** [comment]
The release wasn't properly uploaded on conda and pip, it should be fixed now.

**Comment by Pyligent** [comment]
Thanks so much!
