### ISSUE TITLE
Can't import fastai2 on 11/23/2019

### ISSUE THREAD

**Issue by tumbleintoyourheart** [fastai/fastai_dev#307]
Hi,

Today I can't do any import with fastai2 after `pip install git+https://github.com/fastai/fastai_dev`, it always gives the following error. I tried both Colab and Local.
Everything was fine yesterday 11/22/2019.

![Capture](https://user-images.githubusercontent.com/41382543/69477526-d8a6c200-0e19-11ea-9e9e-7dfc580457ad.PNG)

**Comment by sgugger** [comment]
We changed the inner structure so you have to reset any state you had (I don't know how to do this in colab but in a local dev install, you just need to remove the file that begins by `fastai2-egg` in your site-package.
