### ISSUE TITLE
 'from fastai2.torch_basics import * ' problem(ModuleNotFoundError) on the Kaggle platform

### ISSUE THREAD

**Issue by Pyligent** [fastai/fastai_dev#308]
It happens today on the Kaggle platform.
1. !pip install git+https://github.com/fastai/fastai_dev (Success)
2. When  'from fastai2.torch_basics import *', the error messages are shown.

** Error Messages **
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-04a33ebf1402> in <module>
----> 1 from fastai2.torch_basics import *
      2 from fastai2.test import *
      3 from fastai2.layers import *
      4 from fastai2.data.all import *
      5 from fastai2.optimizer import *

/opt/conda/lib/python3.6/site-packages/fastai2/torch_basics.py in <module>
      1 from torch import multiprocessing
----> 2 from .core.all import *
      3 from .torch_imports import *
      4 from .torch_core import *
      5 from .layers import *

/opt/conda/lib/python3.6/site-packages/fastai2/core/all.py in <module>
      4 from .utils import *
      5 from .script import *
----> 6 from .transform import *

/opt/conda/lib/python3.6/site-packages/fastai2/core/transform.py in <module>
     11 from .dispatch import *
     12 from ..test import *
---> 13 from nbdev.showdoc import show_doc
     14 
     15 #Cell

ModuleNotFoundError: No module named 'nbdev'

**Comment by muellerzr** [comment]
You also need to install nbdev along with it now. pip install nbdev

**Comment by sgugger** [comment]
Should all be fixed but you need to switch to the [fastai v2 repo](https://github.com/fastai/fastai2).

**Comment by Pyligent** [comment]
Thanks so much!
